### ISSUE TITLE
Any particular reason for the fork?

### ISSUE THREAD

**Issue by mitar** [sudomesh/tunneldigger#3]
I see that "This branch is 27 commits ahead, 26 commits behind wlanslovenija:master". I worry that codebases will diverge too much? Any interest in making pull requests for your changes upstream?

**Comment by max-b** [comment]
Hey yeah we diverged mostly because we were using the repo more for a more testing environment than anything else. We had a mini-mesh setup through an server exit and we wanted to be able to commit new changes in order to keep track of them (for lack of more sophisticated dev-ops process). 

I agree it's worth it to try to keep the codebases from diverging too much. We issued a pull request for one of the things we wanted to be included upstream (it was accepted - thanks!) and there's probably a commit or two that I'd like to add, but other than that, I don't think they belong in the upstream repo. 

I can get around to cleaning that up soon.

**Comment by mitar** [comment]
Ah, I exactly know what you are talking about. :-) It is really useful to keep all testing and debugging things in the `git` as well. What I do is try to keep `master` branch always exactly the same as upstream, and then have a special branch for custom stuff. That branch is often then some random commits + all merged feature branches I made upstream pull requests for, but they have not yet been merged. In this way it is not a problem if some change was not yet merged upstream, I can already use my stuff in my branch. But then if some pull request does not get merged upstream, my `master` does not contain stuff which will never be upstream. I name those branches based on the organization behind the fork.

Examples:
* https://github.com/wlanslovenija/django/tree/wlanslovenija
* https://github.com/peerlibrary/meteor/tree/peerlibrary

You can even make that branch the default one in your fork, like we did here: https://github.com/peerlibrary/meteor (see that it is the "peerlibrary" branch which opens).

You can then even nicely see all differences between the upstream and your branch: https://github.com/peerlibrary/meteor/compare/master...peerlibrary

Anyway, this is now starting to sound like preaching how you should be doing stuff. I just wanted to share some best practices based on my own experience.

**Comment by max-b** [comment]
I finally got our repos back in sync! (after more than a month....)

Anyhoo - I just submitted a pull request for a kind of small piece. One of our developers is working on a bit of the client, but it's not ready yet. I'll definitely issue another pull-request when we have it.
